name: Code Quality (Non-blocking)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail the workflow
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev cmake build-essential cppcheck
        
    - name: Run basic code analysis
      run: |
        echo "Running basic code quality checks..."
        cppcheck --enable=warning,style --quiet src/ include/ || true
        echo "Code quality check completed (non-blocking)"
        
    - name: Build verification
      run: |
        cmake -S . -B build
        cmake --build build
        echo "Build verification successful"

